# 线上配置文件
# @author <a href="https://github.com/Chushiyuecsy">程序员狗哥</a>
# @from <a href="https://1098756598.qzone.qq.com/">狗哥的企鹅空间</a>
server:
  port: 8121
spring:
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/znoj
    username: root
    password: Tf8FyZJQpeHwdSbH
#    password: 123456
  # Redis 配置
#  redis:
#    database: 1
#    host: localhost
#    port: 6379
#    timeout: 5000
#    password: Tf8FyZJQpeHwdSbH
  # Elasticsearch 配置
#  elasticsearch:
#    uris: http://dogoj.59888888.xyz:9200
#    username: root
#    password: Tf8FyZJQpeHwdSbH
mybatis-plus:
  configuration:
    # 生产环境关闭日志
    log-impl: ''
# 接口文档配置
knife4j:
  basic:
    enable: true
    username: root
    password: 123456
